### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'isCE')

### ISSUE THREAD

**Issue by song7777** [liamrad/datepicker-enhanced#2]
### Describe the bug

TypeError: Cannot read properties of null (reading 'isCE') 

### Reproduction

no

### System Info

```Shell
"vue": "^3.2.47"
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by byronogis** [comment]
fixed in v2.2.0
