### ISSUE TITLE
size属性不起作用，希望支持

### ISSUE THREAD

**Issue by caveychen** [liamrad/datepicker-enhanced#5]
### Clear and concise description of the problem

设置size='' | 'large' | 'default' | 'small'，希望能控制输入框大小

### Suggested solution

设置size='' | 'large' | 'default' | 'small'，希望能控制输入框大小

### Alternative

设置size='' | 'large' | 'default' | 'small'，希望能控制输入框大小

### Additional context

设置size='' | 'large' | 'default' | 'small'，希望能控制输入框大小

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by byronogis** [comment]
Support since v2.2.1.
