### ISSUE TITLE
因导入该组件的CSS，导致全局CSS被污染

### ISSUE THREAD

**Issue by caveychen** [liamrad/datepicker-enhanced#7]
### Describe the bug

我的页面用到了el-scrollbar组件，
不导入datepicker-enhanced组件，全局样式没有任何问题，
按照文档导入datepicker-enhanced组件样式，
import 'datepicker-enhanced/dist/style.css'
全局样式就被污染了。

例如，datepicker-enhanced组件如下代码修改了我的全局样式
.el-scrollbar {
	--el-scrollbar-opacity: .3;
	--el-scrollbar-bg-color: var(--el-text-color-secondary);
	--el-scrollbar-hover-opacity: .5;
	--el-scrollbar-hover-bg-color: var(--el-text-color-secondary);
	height: 100%;
	overflow: hidden;
	position: relative
}

### Reproduction

Reproduction

### System Info

```Shell
VUE 3 + element-plus
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by byronogis** [comment]
方便的话可以提供一个在线复现, 例如利用 https://stackblitz.com

可以考虑通过 css layer 方式引入组件样式, 以确保项目的自定义样式优先级靠前

**Comment by caveychen** [comment]
我是后端开发，不是专业的前端开发，但是我了解到，这个应该不是引用方式导致的，VUE组件的开发者应该使用scoped 限定组件的css的作用域，应该是这样吧？

**Comment by caveychen** [comment]
我看了下咱们组件的样式表，建议在根HTML元素定义个根CLASS，
不管哪种限定方式，从根本解决问题。

因为我的项目页面比较大，不方便贴出代码，
但是以组件目前的写法，个别项目中一定会出现污染全局的问题。

**Comment by byronogis** [comment]
项目中有使用组件库组件的情况, 这样引用组件的 scope 并不会影响到引入的组件样式

最方便的方法还是像上面说的使用 css layer 引入, 或者直接在main里面放到项目自定义样式前导入, 保证优先级

**Comment by caveychen** [comment]
哥，我是后端开发，你说的css layer引入具体怎么操作，能给个代码示例吗？

**Comment by byronogis** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/CSS/@layer

**Comment by caveychen** [comment]
我也不少写CSS，这种@layer写法很少见，浏览器兼容性很差吧？
![image](https://github.com/user-attachments/assets/721cfc04-db14-4995-bfaf-ac1c23de4388)
官方也提示兼容性可能有问题

**Comment by byronogis** [comment]
> 或者直接在main里面放到项目自定义样式前导入, 保证优先级

mdn页面底部有兼容性表格参考, 或者使用上面说的另一个方法

(现在我写项目其实已经会完使用 css layer 进行结构分层了, 降低下心智负担

**Comment by caveychen** [comment]
你可能对我的问题有误解，我现在的问题是：我的页面的左边栏使用了el-scrollbar组件，因为导入了datepicker-enhanced组件样式，导致我的左边栏出现问题，如果不导入就没有问题。

.el-scrollbar {
--el-scrollbar-opacity: .3;
--el-scrollbar-bg-color: var(--el-text-color-secondary);
--el-scrollbar-hover-opacity: .5;
--el-scrollbar-hover-bg-color: var(--el-text-color-secondary);
height: 100%; **// 这行删除就没有问题了**
overflow: hidden;
position: relative
}

现在的问题不是datepicker-enhanced组件显示有问题，按照你说的提升优先级不能解决我的左边栏的问题

**Comment by caveychen** [comment]
我学习了下 css layer 方案，兼容性一般，劳烦您在建议在根HTML元素定义个根CLASS，是不是更好

**Comment by byronogis** [comment]
> .el-scrollbar {\n--el-scrollbar-opacity: .3;\n--el-scrollbar-bg-color: var(--el-text-color-secondary);\n--el-scrollbar-hover-opacity: .5;\n--el-scrollbar-hover-bg-color: var(--el-text-color-secondary);\nheight: 100%; // 这行删除就没有问题了\noverflow: hidden;\nposition: relative\n}

这些 css 是你自定义的还是这个仓库的产物

**Comment by caveychen** [comment]
是你的组件的CSS

**Comment by byronogis** [comment]
那直接通过高优先级 css 选择器进行 height: unset; 覆盖就好呀

**Comment by caveychen** [comment]
我觉得这不是一个好的方案，
height: unset;能解决这一个问题，但是其他地方出现冲突都要采用类似的覆盖方案吗，
有几十处冲突就要覆盖几十处吗？
我还是希望你那边从根本性解决问题，比如定义一个根Class，CSS统一放在根Class下，如果实在很难做到，我只能fork这个项目，自己做，但是我肯定不希望这样

**Comment by byronogis** [comment]
首先你可以通过搜索在仓库，仓库中并未没有定义此样式，这是由于仓库使用的elementplus中组件生成的

再次，你完全可以在 main 中引入的全局样式中覆盖一次即可

**Comment by caveychen** [comment]
![image](https://github.com/user-attachments/assets/6b93e8c5-bcea-439b-bb00-cbe647312296)
我前面提到的代码，是在你的dist目录下找到的：\node_modules\datepicker-enhanced\dist

**Comment by byronogis** [comment]
> 仓库中并未没有定义此样式，这是由于仓库使用的elementplus中组件生成的

讲过了， 这是仓库使用外部的组件生成的

**Comment by caveychen** [comment]
我把导入CSS的那行代码删除了：import 'datepicker-enhanced/dist/style.css'
发现冲突问题解决了，datepicker-enhanced组件样式也没有出现问题，
我测试几个页面都没有问题，所以这个CSS文件是不是可以不导入？

**Comment by byronogis** [comment]
不能说完全可以，确保使用组件之前项目中有完整的所依赖的elementplus样式

**Comment by caveychen** [comment]
我明白你的意思，我这边项目确实是可以不导入那个CSS文件的，这下问题都解决了，
因为我只是少部分页面使用这个组件，你说的在main中覆盖的方案我是很不情愿的，
麻烦你这么长时间了，非常感谢！
很棒的组件！
